platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-coverity
    username: gpdb
    password: a7vBWDg3mlMv
inputs:
  - name: gpdb_src
outputs:
  - name: gpdb_coverity_artifacts
run:
  path: gpdb_src/concourse/scripts/scan_with_coverity.bash
params:
  OUTPUT_ARTIFACT_DIR: gpdb_coverity_artifacts
  IVYREPO_HOST: repo.pivotal.io
  IVYREPO_PASSWD: 7wdLJRV4HW2q
  IVYREPO_REALM: Artifactory Realm
  IVYREPO_USER: build_readonly
